# Generated by Django 5.0.1 on 2024-02-14 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0012_alter_additionalein_report_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federalaward",
            name="report_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dissemination.general",
                to_field="report_id",
            ),
        ),
    ]
