# Generated by Django 5.0.1 on 2024-02-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0013_alter_federalaward_report_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federalaward",
            name="report_id",
            field=models.TextField(
                help_text="GSAFAC generated identifier", verbose_name="Report ID"
            ),
        ),
    ]
