# Generated by Django 5.0.1 on 2024-02-20 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0013_alter_additionalein_report_id_and_more"),
        ("dissemination", "0014_alter_federalaward_report_id"),
    ]

    operations = []
